import Navigation from "./components/layouts/Navigation";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="container mx-auto px-4">
          <header className="flex justify-end max-w-max">
            <Navigation />
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
